# Generated by Django 4.0.6 on 2022-07-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_component', models.CharField(choices=[('keyboard', 'teclado'), ('mouse', 'raton'), ('display', 'monitor'), ('speaker', 'altavoz'), ('motherboard', 'placa'), ('processor', 'procesador')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InputDevice',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.component')),
                ('mark', models.CharField(max_length=50)),
            ],
            bases=('app.component',),
        ),
        migrations.CreateModel(
            name='InternalDevice',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.component')),
                ('mark', models.CharField(max_length=50)),
            ],
            bases=('app.component',),
        ),
        migrations.CreateModel(
            name='OutputDevice',
            fields=[
                ('component_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.component')),
                ('mark', models.CharField(max_length=50)),
            ],
            bases=('app.component',),
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.outputdevice',),
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('inputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.inputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.inputdevice',),
        ),
        migrations.CreateModel(
            name='MotherBoard',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.internaldevice',),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('inputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.inputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.inputdevice',),
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('internaldevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.internaldevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.internaldevice',),
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('outputdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.outputdevice')),
                ('quantity', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('app.outputdevice',),
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.FloatField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.display')),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.keyboard')),
                ('motherboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.motherboard')),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mouse')),
                ('processor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processor')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.speaker')),
            ],
        ),
    ]
