# Generated by Django 4.0.6 on 2022-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_orderdetailcomputer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetailcomputer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
